spring.application.name=user-service
server.port=8081
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-user:5432/userdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_svc}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:user_svc}
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.jpa.open-in-view=false
spring.jackson.deserialization.accept-float-as-int=false
