spring.application.name=finance-monolito
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:finance}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:finance}
spring.jpa.hibernate.ddl-auto=update
server.port=8080
