spring:

  application:
    name: api-gateway

  cloud:

    gateway:

      server:

        webflux:

          routes:

            - id: history-service
              uri: lb://trade-service
              predicates:
                - Path=/api/users/*/trades

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users,/api/users/**

            - id: market-service
              uri: lb://market-service
              predicates:
                - Path=/api/quotes/**

            - id: trade-service
              uri: lb://trade-service
              predicates:
                - Path=/api/trades/**


server:

  port: 8080


eureka:

  client:

    service-url:

      defaultZone:
        ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}

  instance:

    prefer-ip-address: true


management:

  endpoints:

    web:

      exposure:

        include:
          - health
          - info