spring:

  application:
    name: market-service


server:

  port: 8082


eureka:

  client:

    service-url:

      defaultZone:
        ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}


  instance:

    prefer-ip-address: true


management:

  endpoints:

    web:

      exposure:

        include:
          - health
          - info