spring:

  application:
    name: financial-monolith

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/finance}
    username: ${SPRING_DATASOURCE_USERNAME:finance}
    password: ${SPRING_DATASOURCE_PASSWORD:finance}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    deserialization:
      accept-float-as-int: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info